---
abstract: 'Create easily identifiable gdb breakpoints in Perl parser code.'
author:
  - 'Matthew Horsfall (alh) <wolfsage@gmail.com>'
build_requires:
  Test::More: 0.88
  perl: 5.011002
configure_requires:
  ExtUtils::MakeMaker: 0
  perl: 5.011002
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-GDB-Parser-Breakpoint
no_index:
  directory:
    - t
    - inc
requires:
  Devel::GDB::Breakpoint: 0.01
  Parse::Keyword: 0.06
  perl: 5.011002
version: 0.01
